### PR TITLE
Run chat handlers in separate threads

### PR DESCRIPTION
**Pull request by byroot**
First I don't really expect this to be merged, it's more to have your opinion on the matter.

My issue is that from my understanding of the code, even though the http routes are executed in puma threads, the chat routes are all executed synchronously in the main thread (I might have missed something though).

This can easily be tested:
```ruby
class FastAndSlow < Lita::Handler
  route 'slow' do |response|
    sleep 3
    response.reply("Slow!")
  end

  route 'fast' do |response|
    response.reply("Fast!")
  end
end
```

Then in the chat it will look like this:
```
me> lita fast
lita> Fast!
me> lita slow
me> lita fast
lita> Slow!
lita> Fast!
```

After the patch
```
me> lita fast
lita> Fast!
me> lita slow
me> lita fast
lita> Fast!
lita> Slow!
```

So both code review and experimentation tells me only a single chat handler can be possibly running at once.

Which is problematic when you shell out to slow sub processes or call slow HTTP endpoints.

I quickly experimented that patch and it seems to works fine, but our Lita instance is still quite small, so do you think we might run into much troubles with that patch? Since the HTTP handlers are already threaded I assume not, but I'd love a second opinion.

### CODE REVIEW

**Comment by jimmycuadra** [comment]
Thanks for bringing this up. Concurrency for chat routes is actually handled by each individual adapter and not Lita itself. The concurrency mechanism usually involves multithreading, but it may vary between adapters. If you're using the Slack adapter, you may be experiencing the issue being discussed in #77. If that's the case, we'd appreciate more input on the discussion there to figure out a way to prevent long running chat routes from blocking the main event loop.

**Comment by byroot** [comment]
I indeed noticed the issue was somewhat similar to #77.

Can you name an adapter that handle threading properly? I'm willing to investigate how we could implement the slack adapter in a proper way.

**Comment by jimmycuadra** [comment]
I believe both the IRC and HipChat adapters will run chat routes concurrently. Neither of them manage threads directly – they are managed by the underlying protocol libraries for each, cinch for IRC and xmpp4r for HipChat.

**Comment by byroot** [comment]
Ok, that makes sense. I will investigate how I can add threading support in the slack adapter directly.

**Comment by jimmycuadra** [comment]
It does use threads, but through Eventmachine. Eventmachine creates an event loop on a single thread and then spawns a thread pool for workers. The issue right now is that the chat routes are being called from the main thread. You can defer long running code yourself with some Eventmachine methods inside your chat route, but that isn't really an acceptable solution long term. The adapter should be creating workers (probably via `EM.defer`) and then invoking the chat route from the new worker.

**Comment by byroot** [comment]
Yep that's why I figured by opening `lita-slack` code. It was really obvious.

I quickly tested it seems to works very well. I'll do some more extended testing tomorrow.

**Comment by jimmycuadra** [comment]
As we discovered in kenjij/lita-slack#21, this issue does, in fact, require changes to Lita itself. Spawning a new thread before calling `dispatch_to_route` is essentially the right idea, but it needs to be abstracted so that adapters can provide their own concurrency mechanism.

What I imagine is a new adapter method like `Lita::Adapter#run_concurrently` which simply yields the provided block by default, making it an effective no-op. An adapter can choose to override this method to provide its own concurrency mechanism. In the case of lita-slack, it'd look like this:

``` ruby
def run_concurrently
  EventLoop.defer { yield }
end
```

Then `Lita::Handler::ChatRouter#dispatch` can use `run_concurrently` instead of spawning a thread.

If you want to take a stab at implementing it here in this PR, go for it. If not, I will look into it soon.

Thanks again for reporting this issue and helping work out the solution.

**Comment by jimmycuadra** [comment]
I played around with this idea a bit and I think changing the current behavior might introduce some subtle errors in existing plugins. I think I'm going to wait on it for now – it's probably a good candidate for a Lita 5.0 change.

**Pull request closed without merging**
